### PR TITLE
Fix table formatting

### PR DESCRIPTION
**Pull request by paulidale**
The table wasn't rendering at all due to a missing blank line.

Sigh.

### CODE REVIEW

**Comment by paulidale** [comment]
Could the second approver please merge ASAP this?

It's not a good look on the web site currently.

**Review by hlandau — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
Pushed.

**Comment by t8m** [comment]
Unfortunately it did not seem to help?

**Comment by paulidale** [comment]
It looked fine in preview.  Probably needs some investigation into the HTML we produce...

**Comment by t8m** [comment]
It seems the HTML formatter is not able to handle it correctly. It simply does not recognize the table.

**Pull request closed without merging**
