### PR TITLE
make markdown markup consistent

### PR DESCRIPTION
**Pull request by quarckster**

### CODE REVIEW

**Review by nhorman — APPROVED** [review]
I'm fine with these changes, but the # style differs from the style we use in the openssl repo, do we want to be consistent in all our repositories, or does it not matter?

**Review by levitte — APPROVED** [review]

**Comment by levitte** [comment]
Made this a minor edit, 'cause it is

**Comment by quarckster** [comment]
> similar to Neil. Looks good, although keen to learn the motivation.

The motivation is consume the content of these repositories during the website building and to have less hacks in the build script.

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Merged. Thank you.

**Pull request closed without merging**
