### PR TITLE
Constant time BIGNUM vote

### PR DESCRIPTION
**Pull request by paulidale**
At the moment, this is a draft of the vote for comment.

Addressing this six years ago would, likely, have saved us engineer time.

We've can likely use David's BoringSSL implementation as a reference for any work required.

### CODE REVIEW

**Comment by levitte** [comment]
Link to the mentioned issue: openssl/openssl#6640

**Comment by beldmit** [comment]
+1

**Comment by paulidale** [comment]
@beldmit, we're not at the voting stage.  I'll raise that next week after feedback over this suggestion.

**Comment by paulidale** [comment]
No comments over the last few days, so calling the vote:
```
Topic: The OTC recommends that the implementation of constant time BIGNUM
       gets high priority.
Comment: This was raised over six years ago by David Benjamin in #6640.
          Unfortunately, engineering efforts have continued to be diverted
          towards fixing timing issues on an ad-hoc basis.
```

**Comment by paulidale** [comment]
Vote +1

**Comment by beldmit** [comment]
+1

**Comment by levitte** [comment]
+1

**Comment by slontis** [comment]
+1

**Comment by paulidale** [comment]
One more +1 and this vote passes....

**Comment by mattcaswell** [comment]
+0

**Comment by t8m** [comment]
+0

**Comment by hlandau** [comment]
+1

**Comment by t-j-h** [comment]
+0

**Comment by paulidale** [comment]
The vote passes.

**Comment by kroeckx** [comment]
Voting +1

**Pull request closed without merging**
